#!/bin/sh
#/etc/init.d/jukebox

### BEGIN INIT INFO
# Provides:          jukebox
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       The jukebox service
### END INIT INFO

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

case "$1" in
start)
exec forever --sourceDir=/home/pi/jukebox -p //home/pi/jukebox jukebox.js
;;
stop)
exec forever stop --sourceDir=/home/pi/jukebox jukebox.js
;;
*)
echo "Usage: /etc/init.d/myService {start|stop}"
exit 1
;;
esac
exit 0

